language: python
python:
  - "3.6"
  - "2.7"
before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox
  - pip install tox-travis
  - pip install .
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - tox

after_sucess:
  coveralls
